require File.join(File.dirname(__FILE__), "is_taggable", "is_taggable")
require File.join(File.dirname(__FILE__), "is_taggable", "is_tagger")
require File.join(File.dirname(__FILE__), "is_taggable", "tag_list")
require File.join(File.dirname(__FILE__), "is_taggable", "tags_helper")
require File.join(File.dirname(__FILE__), "is_taggable", "tagging")
require File.join(File.dirname(__FILE__), "is_taggable", "string")
